# Generated by Django 4.0.2 on 2022-02-13 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_order_options'),
        ('store', '0013_alter_orderitem_order'),
    ]

    operations = [
    ]
